### ISSUE TITLE
[2.0] Support for Symfony 5.0

### ISSUE THREAD

**Issue by alcaeus** [FriendsOfSymfony/FOSOAuthServerBundle#625] opened 2019-08-26 07:24 UTC
This serves as an epic to collect all issues and pull requests arising with Symfony 5 support.

**Comment by OneEyedSpaceFish** [comment] 2019-11-07 13:52
@alcaeus 
Would that be possible to merge all outstanding PRs for 2.0 into a feature branch?
That way it would be possible for people to start testing their own application with symfony 5.0 beta before it's release.

**Comment by alcaeus** [comment] 2019-11-08 08:24
I'll do a session to take care of Symfony 5 support next week. Sorry for the delay here, but I've been quite busy with @doctrine packages.

**Comment by cpjolly** [comment] 2019-11-09 22:06
I don't see it mentioned elsewhere so please note that the base server library FriendsOfSymfony/oauth2-php will also need a few minor incremental  changes to support Symfony 5. For example, it's composer.json requires `"symfony/http-foundation": "~3.0|~4.0"`

**Comment by OneEyedSpaceFish** [comment] 2019-11-19 10:35
@alcaeus 
Do you need a hand with the migration?
If you explain what you planned to do, I wouldn't mind taking a look.

**Comment by alcaeus** [comment] 2019-11-19 10:36
In a nutshell:
* Update composer constraints to allow Symfony 5
* Ensure Symfony 5 is tested on travis-ci
* Update code to avoid breakages and deprecations due to Symfony
* repeat above until build is stable

If you're interested, please go ahead 👍

**Comment by OneEyedSpaceFish** [comment] 2019-11-19 10:47
@alcaeus Are there any pending PRs that you would like to include in this change request?

**Comment by alcaeus** [comment] 2019-11-19 11:33
Taking a quick look, you want to check out #599, #610, #617, #619, and #623 - they sound like they could affect this. I'd have to take a closer look to know for sure.

**Comment by cpjolly** [comment] 2019-11-24 16:09
@alcaeus I can confirm that the issues described in #623 are the same for Symfony 5.0

**Comment by OneEyedSpaceFish** [comment] 2019-11-25 10:16
Just an FYI; I started to have a look at this, but there's no much progress made so far, as I'm extremely busy nowadays and have very little time.

So if someone would like to have a look before I can sort this out, feel free to do so.

**Comment by sci3ma** [comment] 2019-12-22 11:40
Any updates when we can use FOSOAuthServerBundle with Symfony 5?

**Comment by OneEyedSpaceFish** [comment] 2019-12-23 14:06
@sci3ma none from me yet, I've been too busy with work.
Feel free to have a look

**Comment by elchris** [comment] 2020-01-17 06:28
I've started some work on my fork here: https://github.com/elchris/FOSOAuthServerBundle/tree/symfony-5

it also references another fork of mine for the oauth2-php project

i just got the tests to "compile", resolved composer dependencies, etc.

- composer install
- ./vendor/bin/phpunit

Errors: 21, Failures: 6, Warnings: 18, Incomplete: 2.

If anyone wants to submit to me a pull request against my "symfony-5" branch with some incremental fixes to the tests, i'd be cool with that. heh.

**Comment by elchris** [comment] 2020-01-18 01:58
Also this is relevant: https://stackoverflow.com/questions/56438177/deprecated-the-listenerinterface-turn-your-listeners-into-callables-instead in OAuthListener.php as Symfony\Component\Security\Http\Firewall\ListenerInterface was deprecated.

I let Nicolas Grekas know about [this article](https://symfony.com/doc/current/components/security/firewall.html) which still references it.

**Comment by elchris** [comment] 2020-01-18 04:56
since we use a deprecated PHPUnit method assertArraySubset, I looked at this https://github.com/sebastianbergmann/phpunit/issues/3494#issuecomment-464464423

and added a reference to https://packagist.org/packages/dms/phpunit-arraysubset-asserts

**Comment by elchris** [comment] 2020-01-19 03:56
Now down to:
Tests: 186, Assertions: 446, Warnings: 5, Incomplete: 3.

Still need to deal with deprecated reference to SecurityContextInterface ... not sure why tests aren't failing against that though.

**Comment by elchris** [comment] 2020-01-22 23:28
Before I forget: two tests had already been marked as incomplete but I added one more as incomplete: testProcessWithoutExistingTokenStorage:

$this->markTestIncomplete('Find a graceful way to handle what happens when no token storage is available');

**Comment by elchris** [comment] 2020-01-25 06:29
ok i'm down to 2 warnings which i can't really find a way to fix so I'll leave them be.

1) FOS\OAuthServerBundle\Tests\Document\AuthCodeManagerTest::testDeleteExpired
Method getQuery may not return value of type Mock_AbstractQuery_84acf880, its return declaration is ": Doctrine\ODM\MongoDB\Query\Query"

2) FOS\OAuthServerBundle\Tests\Document\TokenManagerTest::testDeleteExpired
Class "Doctrine\ODM\MongoDB\Query\Query" is declared "final" and cannot be mocked.

as far as SecurityContextInterface goes, it looks like it's only referenced in a test as a fall-back for when a TokenStorageInterface was not available, and I imagine it was a backward-compatibility thing, and from what I can tell that part of the test doesn't get executed because the TokenStorage is there.

Ok so with this last commit to my branch, I could in theory perpetrate a pull request ...

The tests all pass as far as ./vendor/bin/phpunit goes. Are there some other tests I should run?

Also I would need to send-in a pull-request for the other project "oauth2-php" https://github.com/elchris/oauth2-php/tree/symfony-5 which would also be backward-incompatible and would need a separate version branch in the original project.

So ...... to recap:

1. I could use some guidance from the maintainers of the [oauth2-php project](https://github.com/FriendsOfSymfony/oauth2-php) as to whether I should send-in a pull-request of [my fork](https://github.com/elchris/oauth2-php/tree/symfony-5), and into which branch
2. I would appreciate if some folks could check out my fork of **/this/** project here: https://github.com/elchris/oauth2-php/tree/symfony-5 and guide me as to whether or not I should send-in a pull request, and if so, into which branch

**Comment by OneEyedSpaceFish** [comment] 2020-02-03 09:55
@alcaeus fyi

**Comment by anboo** [comment] 2020-02-03 12:49
FYI

**Comment by patrickbussmann** [comment] 2020-02-10 21:07
@elchris can you make a pull request? 👍 
Looks great.

**Comment by elchris** [comment] 2020-02-10 21:53
ok I'll make a pull request shortly, and ya'll can let me know later what you want me to do for oauth2-php

**Comment by patrickbussmann** [comment] 2020-02-10 21:56
Yes please make for both repositories because we need for installation 👍

**Comment by elchris** [comment] 2020-02-13 17:30
> Yes please make for both repositories because we need for installation 👍

ok sounds good, I'll try to do it later tonight.

**Comment by iisisrael** [comment] 2020-02-13 18:47
@elchris I'm working through some clean-up forked from your fork, and I'm wondering why the Symfony templating component was removed from the `AuthorizeController` service configuration?  The component itself is still supported in v5, only deprecated from framework integration in 4.3.

This _could_ be changed to depend on `Twig\Environment` instead, but that's a BC break not required for Symfony 5 support, right?  Or am I missing something?

**Comment by elchris** [comment] 2020-02-13 19:00
> @elchris I'm working through some clean-up forked from your fork, and I'm wondering why the Symfony templating component was removed from the `AuthorizeController` service configuration? The component itself is still supported in v5, only deprecated from framework integration in 4.3.
> 
> This _could_ be changed to depend on `Twig\Environment` instead, but that's a BC break not required for Symfony 5 support, right? Or am I missing something?

I can look at it, and of course, I can't speak for the maintainers of this package but I **imagine** that the goal would be to arrive at something that is compatible **and** deprecation-warning-free in a 4.4/5.0.* context, such that a new release might be cut from it, which is backward-incompatible with anything earlier than 4.4?

But I'm definitely open to suggestions because I'm more or less "flying blind" as I'm making a lot of assumptions.

**Comment by iisisrael** [comment] 2020-02-13 21:07
@elchris I poked around a bit for a solution, but it seems that trying to hand-roll a templating service would be a bit beyond the scope of S5 compatibility.  That could be a future improvement if someone wanted to do that or otherwise add a third-party templating service.  Twig it is.

I also clarified the authentication listener handling, which shouldn't ever have been expected to return anything.

Some other minor clean-up, dev environment improvements.

There's a little more polish that can be done, noted on the PR on your fork.  I can look at that tomorrow.

**Comment by elchris** [comment] 2020-02-13 21:21
> @elchris I poked around a bit for a solution, but it seems that trying to hand-roll a templating service would be a bit beyond the scope of S5 compatibility. That could be a future improvement if someone wanted to do that or otherwise add a third-party templating service. Twig it is.
> 
> I also clarified the authentication listener handling, which shouldn't ever have been expected to return anything.
> 
> Some other minor clean-up, dev environment improvements.
> 
> There's a little more polish that can be done, noted on the PR on your fork. I can look at that tomorrow.

Oh that's very cool. I'll try to look at it and merge it in tonight, thank you so much for doing this.

**Comment by elchris** [comment] 2020-02-14 01:38
@iisisrael I merged your PR into my branch, thank you.

**Comment by elchris** [comment] 2020-02-14 02:20
- I made a PR for [oauth2-php](https://github.com/FriendsOfSymfony/oauth2-php/pull/119)
- I made a PR for [this project](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/639)

Still working on some cleanups on both.

**Comment by elchris** [comment] 2020-02-14 04:02
@iisisrael I just realized they had phpcs and phpstan hooked-up in their CI so I made some updates to travisci config file, applied php-cs-fixer to fix all phpcs issues, but now i'm working thru a flurry of phpstan fails and it's going to take me a while but i'll be committing incrementals.

=> TL;DR: be sure to pull again from my origin into your branch :)

**Comment by elchris** [comment] 2020-02-14 04:21
@iisisrael I added "composer commands" in the "scripts" section of composer.json so now we can:

- composer test
-- ./vendor/bin/phpunit
- composer lint
-- ./vendor/bin/php-cs-fixer fix .
- composer phpstan
-- ./vendor/bin/phpstan analyse --configuration phpstan.neon --level 6 .

**Comment by elchris** [comment] 2020-02-14 19:15
@iisisrael I'll try to tackle as many of the phpstan issues as possible over the weekend. It would appear that all those issues have been around for quite some time, but I'd like to get their CI to pass again.

**Comment by iisisrael** [comment] 2020-02-14 22:58
Made some functional test improvements, will continue over the weekend, and clean up the lint and phpstan results.

**Comment by elchris** [comment] 2020-02-14 23:25
@iisisrael that's great I merged your pull request.

**lint requests should already be clean**.

Priority-wise you might consider:

1. switching my getter/setter additions to production code to reflection class references in tests
2. look at the incomplete tests or just ignore them for now
3. look at phpstan improvements. But if you're busy with the above two I can work on phpstan stuff. What I can do is start from the bottom of the list of the phpstan warnings, and if you do get around to phpstan, you could start from the top of the list.

**Comment by elchris** [comment] 2020-02-16 01:35
@iisisrael I'm removing the reference to DefinitionDecorator in OAuthFactory test because [it was deprecated as of Symfony 3.3](https://symfony.com/blog/new-in-symfony-3-3-dependency-injection-deprecations)

**Comment by elchris** [comment] 2020-02-16 03:29
@iisisrael Updates:

**Please be sure to pull from my branch**

I've cleaned-up a lot of obvious "return type missing" phpstan issues starting from the bottom up, mostly in the tests, and there are still a bunch of those starting from the top in the production code,  but overall, in the tests we're still left with a ton of issues like:

- some assertion will always evaluate to false
- result of void method being used, like an assertNull on a "void" process() method
- iterable types needing to be more specified w/ generics-like type hints

... still overall 200 phpstan errors and 2 warnings. lol.

**Comment by iisisrael** [comment] 2020-02-19 01:22
@elchris, reflection property assertions implemented, removing the getters.

Up next, will fix MongoDB test configurations, where tests are failing with warnings on mocked query builder return value, which can't be mocked (ODM query is a final class) and can't return an ORM query object (return type constraint).  I'm pretty sure mongo can be configured in the Symfony test environment to run with the [in-memory storage engine](https://docs.mongodb.com/manual/core/inmemory/).  I've only ever tested functionally with an actual collection written to disk, but if in-memory is possible, it will have the same advantages as using sqlite for ORM tests.

**Comment by elchris** [comment] 2020-02-19 03:32
@iisisrael Thank you for your work, I just merged your pull request into my branch.

**Comment by patrickbussmann** [comment] 2020-02-19 15:55
Thanks @elchris but I found a issue with anonymous users.
I fixed it here and added a test case but I'm not able to create pull requests.
I already informed GitHub about this issue.

https://github.com/patrickbussmann/FOSOAuthServerBundle/tree/symfony-5-anonymous-access
And now I cant upload pictures because of error message.
I will create a pull request as soon as GitHub fixes the issue.

Else you could merge it directly when you checkout the branch.

Thanks in Advance and in general for your work 👍

Ah lol ok, "You cant comment at this time". Seems to be a bigger GitHub problem 😢

**Comment by cpjolly** [comment] 2020-03-01 11:49
@elchris - I see all the excellent work done by yourself and the other guys, but what's the status of your [fork](https://github.com/elchris/FOSOAuthServerBundle/tree/symfony-5) ? Any idea when it will be "ready" and your changes will show up here ?

**Comment by elchris** [comment] 2020-03-01 18:28
Hi @cpjolly :) As mentioned [here](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/625#issuecomment-586065721)  I did make a pull request from my fork, but I have not yet heard from the maintainers of this project. So I have no idea if and when this will ever get mainstreamed.

And yes for now I would say that it is a good idea to [keep using my fork](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/625#issuecomment-584354536) as you currently are, I will continue to review and accept any and all pull requests to my fork.

Big thanks to @iisisrael & @patrickbussmann for their contributions.

**Comment by elchris** [comment] 2020-03-01 18:36
What would be helpful:

1. For more people to test my fork in their projects, and report back in this thread to tell us what works and what doesn't.
2. If bugs are found, for people to submit pull requests to my fork, and I will review them and merge them
3. To send-in pull requests for "code cleanups" of issues reported by PHPStan, by running **[composer phpstan](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/625#issuecomment-586091212)**, such that we might put their CI script in a position to finally pass. There are **a lot** of issues which if addressed, would definitely make this framework a lot more robust. I have done a bunch, but there are still so many more left, it's **very** tedious. If you are looking to take this on, let us know in this thread such that we don't duplicate efforts. Personally I'm done for a while, but if I do fix a few more, I'll update this thread.

**Comment by sabat24** [comment] 2020-06-04 15:05
I found one issue in the architecture of OAauth2.php lib. I think that [GrantAccessToken](https://github.com/elchris/oauth2-php/blob/symfony-5/lib/OAuth2.php#L683) method shouldn't return the whole response. It should return a newly created token and there should be another method which could build the response.

If I want to override a tokenAction inside my own controller and make some other stuff with the token I need to parse a JSON response from GrantAccessToken method. It's a big problem but I generally expect from model to get a raw data not HTTP response, which should be done inside controller.

**Comment by NielsJanssen** [comment] 2020-06-15 12:34
@elchris 

> What would be helpful:
> 
> 1. For more people to test my fork in their projects, and report back in this thread to tell us what works and what doesn't.

I've installed your fork and have been using it in a very basic OAuth implementation, so far without issues.

**Comment by tmarly** [comment] 2020-07-10 17:01
Just for information, I am using this fork since one month (not in production yet), using the authorization code flow, and I found no issue.
Great job @elchris !

**Comment by deguif** [comment] 2020-09-18 18:16
Symfony 5 is now supported in master branch.
An alpha 2 version will be tagged in the coming days.

**Closed by deguif** 2020-09-18 18:16 UTC
Labels: Enhancement

**Comment by elchris** [comment] 2020-09-18 18:40
@deguif - did i still need to rebase my fork, or are you good now that you have fixed it into master?

**Comment by deguif** [comment] 2020-09-18 18:42
@elchris would be nice if you can rebase as that would allow to see other changes you introduced.
But the better would be that you open small PRs with specific changes ;)

**Comment by lebadapetru** [comment] 2020-09-28 11:50
Hey guys, using symfony 5 and i tried to install this bundle but i get the following:

`The child node "db_driver" at path "fos_oauth_server" must be configured.`

I've added this into my composer.json:
`
{
    "friendsofsymfony/oauth-server-bundle": "dev-master"
}`

**Comment by cpjolly** [comment] 2020-10-13 10:34
Hi @elchris, hi @deguif, 
I did a comparison of head with the [changes](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/compare/master...elchris:symfony-5) in the folk from @elchris. Most seem to have already been implemented in master, so a rebase & smaller PRs of the remaining changes looks like a good idea
