### ISSUE TITLE
Symfony 4 - Non-public service should be made public

### ISSUE THREAD

**Issue by cvele** [FriendsOfSymfony/FOSOAuthServerBundle#529] opened 2018-01-31 09:15 UTC
Since all services are made private by default in Symfony 4, the same applies to `fos_oauth_server.client_manager.default`, which we should be able to fetch publicly from container.

**Comment by dkarlovi** [comment] 2018-01-31 09:16
Duplicate of #520.

**Closed by dkarlovi** 2018-01-31 09:16 UTC
