### ISSUE TITLE
Add Symfony 4 Support

### ISSUE THREAD

**Issue by iCodr8** [FriendsOfSymfony/FOSOAuthServerBundle#498] opened 2018-01-04 14:20 UTC
Add Symfony 4 Support

**Comment by SebScoFr** [comment] 2018-01-04 14:26
Duplicate of #485 
But yes, very impatient for this to happen.

**Comment by dkarlovi** [comment] 2018-01-05 11:16
Merged in #497

**Closed by dkarlovi** 2018-01-05 11:16 UTC
