### ISSUE TITLE
Error: Call to a member function getUser() on null" at AuthorizeController.php line 58

### ISSUE THREAD

**Issue by mappedinn** [FriendsOfSymfony/FOSOAuthServerBundle#425] opened 2016-08-01 03:03 UTC
I am trying to configure [FOSOAuthServerBundle](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle) with [FOSUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle)  using the documentation of FOSOAuthServerBundle. This is the config:
## config.yml

```
fos_user:
    db_driver: orm
    firewall_name: oauth_token #main
    user_class: Minn\UserBundle\Entity\User

fos_oauth_server:
    db_driver: orm
    client_class:        Minn\UserBundle\Entity\Client
    access_token_class:  Minn\UserBundle\Entity\AccessToken
    refresh_token_class: Minn\UserBundle\Entity\RefreshToken
    auth_code_class:     Minn\UserBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager # this is added to fos_oauth to use fos_user for authentication
        options:
            supported_scopes: api
```
## security.yml

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER : ROLE_API
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:      ^/(_(profiler|wdt)|css|images|js)/
            security:     false

        oauth_token:
            pattern:      ^/oauth/v2/token
            security:     false

        api_doc:
            pattern:      ^/api/doc
            security:     false

        api:
            pattern:      ^/api
            fos_oauth:    true
            stateless:    true

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```

A this point, it seems to be working as testing the config with the creation of symfony command worked well.
## The testing command:

```
<?php

namespace Minn\UserBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Acme\OAuthServerBundle\Document\Client;

class CreateOAuthClientCommand extends ContainerAwareCommand {

    protected function configure() {
        $this
                ->setName('oauth:client:create')
                ->setDescription('Creates a new client')
                ->addOption(
                        'redirect-uri', null, InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY, 'Sets redirect uri for client. Use this option multiple times to set multiple redirect URIs.', null
                )
                ->addOption(
                        'grant-type', null, InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY, 'Sets allowed grant type for client. Use this option multiple times to set multiple grant types..', null
        );
    }

    protected function execute(InputInterface $input, OutputInterface $output) {
        $clientManager = $this->getContainer()->get('fos_oauth_server.client_manager.default');
        $client = $clientManager->createClient();
        $client->setRedirectUris($input->getOption('redirect-uri'));
        $client->setAllowedGrantTypes($input->getOption('grant-type'));
        $clientManager->updateClient($client);
        $output->writeln(
                sprintf(
                        'Added a new client with public id <info>%s</info>, secret <info>%s</info>', $client->getPublicId(), $client->getSecret()
                )
        );
    }

}
```
- Run the following symfony command:
  
  ```
  php app/console oauth:client:create --redirect-uri="http://localhost/minnapi/web/app_dev.php/" --grant-type="authorization_code" --grant-type="password" --grant-type="refresh-token" --grant-type="token" --grant-type="client_credentials"
  ```
- the output of the command is:
  
  ```
  Added a new client with public id 5_552osbf54k4c0kow00ko8ww8kkgcwgg4g4okkgc0wcww0ggsw8, secret 10kv0z11wr688o8kws4wg08scs48o4o8o8cg004c44wcgcgc4s
  ```
  
  Please be noted that the command created a record in the table client witch is as follows:
  
  ```
  INSERT INTO `minn_client` (`id`, `name`, `random_id`, `redirect_uris`, `secret`, `allowed_grant_types`) VALUES
  (5, NULL, '552osbf54k4c0kow00ko8ww8kkgcwgg4g4okkgc0wcww0ggsw8', 'a:1:{i:0;s:41:"http://localhost/minnapi/web/app_dev.php/";}', '10kv0z11wr688o8kws4wg08scs48o4o8o8cg004c44wcgcgc4s', 'a:5:{i:0;s:18:"authorization_code";i:1;s:8:"password";i:2;s:13:"refresh-token";i:3;s:5:"token";i:4;s:18:"client_credentials";}');
  ```
- Execute the following request in your browser
  
  ```
  http://localhost/minnapi/web/app_dev.php/oauth/v2/token?client_id=5_552osbf54k4c0kow00ko8ww8kkgcwgg4g4okkgc0wcww0ggsw8&client_secret=10kv0z11wr688o8kws4wg08scs48o4o8o8cg004c44wcgcgc4s&grant_type=client_credentials
  ```
  
  The returned answer of the browser is:
  
  ```
  {"access_token":"Njg5OWUzZmI5Yjg5MWFlYTZkOWNmMWIwNGMwNDNmZDhkZmEwZDhjMDM4OTcyNzZiNzRiMTNiZjBlOGMyMDk0OA","expires_in":3600,"token_type":"bearer","scope":"api"}
  ```

Now, the problems come when I tried to check it with an action in a controller as proposed by the documentation:
## The testing action

```
/**
 * @Route("/connect")
 */
public function connectAction(){
    // 1. creation of a client (manually)
    $clientManager = $this->get('fos_oauth_server.client_manager.default');
    $client = $clientManager->createClient();
    $client->setRedirectUris(array('http://localhost/minnapi/web/app_dev.php/'));
    $client->setAllowedGrantTypes(array('token', 'authorization_code'));
    $clientManager->updateClient($client);

    return $this->redirect($this->generateUrl('fos_oauth_server_authorize', array(
        'client_id'     => $client->getPublicId(),
        'redirect_uri'  => 'http://localhost/minnapi/web/app_dev.php/',
        'response_type' => 'api'
    )));
}
```

The error I got is:

**Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getUser() on null" at /home/amine/NetBeansProjects/minnapi/vendor/friendsofsymfony/oauth-server-bundle/Controller/AuthorizeController.php line 58
Context: { "exception": "Object(Symfony\Component\Debug\Exception\FatalErrorException)" }**

Is there any idea about the error?

Thanks

**Comment by andela-tolotin** [comment] 2016-09-28 06:35
@mappedinn can you paste the whole class file and let me take a look. Because this method doesn't seem to give enough information about the problem

**Comment by andela-tolotin** [comment] 2016-09-28 06:41
@mappedinn does the bundle understand that your client table is `minn_client`

**Comment by mappedinn** [comment] 2016-09-28 06:55
Clients are stored correctly in the table `minn_client`.

My problem is coming from the action `connectAction`. Have any idea?

**Comment by andela-tolotin** [comment] 2016-09-28 07:04
@mappedinn did you extends the BaseClient in your model.

**Comment by andela-tolotin** [comment] 2016-09-28 07:10
@mappedinn can you paste your Entities `(Authcode.php, AccessToken.php, RefreshToken.php, Client.php)` and let me take a look. Your problem is coming from improper model relationship mappings.

**Comment by mappedinn** [comment] 2016-09-28 07:42
Thanks @andela-tolotin for being helpful.

Below are my entities:

```php
<?php

namespace Minn\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * Description of User.
 *
 * @ORM\Entity
 * @ORM\Table(name="minn_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}
```

---

```php
<?php

namespace Minn\OAuthServerBundle\Entity;

use FOS\OAuthServerBundle\Entity\AccessToken as BaseAccessToken;
use Doctrine\ORM\Mapping as ORM;

/**
 * Description of AccessToken.
 *
 * @ORM\Entity
 * @ORM\Table(name="minn_access_token")
 */
class AccessToken extends BaseAccessToken
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Client")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $client;

    /**
     * @ORM\ManyToOne(targetEntity="Minn\UserBundle\Entity\User")
     */
    protected $user;
}
```

---

```php
<?php

namespace Minn\OAuthServerBundle\Entity;

use FOS\OAuthServerBundle\Entity\AuthCode as BaseAuthCode;
use Doctrine\ORM\Mapping as ORM;

/**
 * Description of AccessToken.
 *
 * @ORM\Entity
 * @ORM\Table(name="minn_auth_code")
 */
class AuthCode extends BaseAuthCode
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Client")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $client;

    /**
     * @ORM\ManyToOne(targetEntity="Minn\UserBundle\Entity\User")
     */
    protected $user;
}
```

---

```php
<?php

namespace Minn\OAuthServerBundle\Entity;

use FOS\OAuthServerBundle\Entity\Client as BaseClient;
use Doctrine\ORM\Mapping as ORM;

/**
 * Description of Client.
 *
 * @ORM\Entity
 * @ORM\Table(name="minn_client")
 */
class Client extends BaseClient
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

     /**
      * @var string
      * @ORM\Column(name="name", type="string", length=255, nullable=true)
      */
     protected $name;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return Client
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
}
```

---

```php
<?php

namespace Minn\OAuthServerBundle\Entity;

use FOS\OAuthServerBundle\Entity\RefreshToken as BaseRefreshToken;
use Doctrine\ORM\Mapping as ORM;

/**
 * Description of RefreshToken.
 *
 * @ORM\Entity
 * @ORM\Table(name="minn_refresh_token")
 */
class RefreshToken extends BaseRefreshToken
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Client")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $client;

    /**
     * @ORM\ManyToOne(targetEntity="Minn\UserBundle\Entity\User")
     */
    protected $user;
}
```

**Comment by andela-tolotin** [comment] 2016-09-28 08:54
@mappedinn line 58 of the Authorization.php is `$user = $this->getTokenStorage()->getToken()->getUser();`. You need to login first so the the bundle can retrieve the user information from the token storage.

**Comment by mappedinn** [comment] 2016-09-28 09:35
thanks again!

Can you give the complete code of the action? (I feel I am totally lost)

**Comment by andela-tolotin** [comment] 2016-09-28 09:39
@mappedinn I think we will need to pair may be on google hangout for this. send me an invite to this email `olotintemitope@gmail.com`

**Comment by mappedinn** [comment] 2016-09-28 10:21
thanks for being so helpfull... I just sent an invitation on hangouts ;)

**Comment by andela-tolotin** [comment] 2016-09-28 10:28
@mappedinn not an invitation to a conversation, send me a hangout link.

**Comment by dre0** [comment] 2016-11-16 07:18
what security should be used for oauth/v2/auth

**Comment by andela-tolotin** [comment] 2016-11-16 10:24
@dre0 you question is not clear to me. do you mean security settings in the security.yml file?

**Comment by dre0** [comment] 2016-11-18 11:23
@andela-tolotin yes,i can't figuere out correct firewall setting for oauth/v2/auth path. should it be a form login secured or fos secured(requiring access token).

**Comment by andela-tolotin** [comment] 2016-11-19 07:28
@dre Your configuration for oauth/v2/auth should be under the firewall and under 

```oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider:       fos_userbundle # user provider
                login_path:     #path to your login
                check_path:     #path to your login check
            anonymous: false```

and your `oauth/v2/token` should be above the form login and main/app firewall

```oauth_token:
            pattern:      ^/oauth/v2/token
            security:     false```

**Comment by dinamic** [comment] 2018-01-26 12:12
I agree with @andela-tolotin. The issue is caused by the lack of firewall protecting the `^/oauth/v2/auth` end-point.

@mappedinn, could you please close the issue if the matter is resolved?

**Closed** 2018-01-26 15:32 UTC
